name: Backend CI / Test

on:
  pull_request:
    branches: [main, master]
    paths:
      - 'apps/fumufumu-backend/**' # バックエンドのコードが変更された時だけ実行
      - '.github/workflows/be-test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/fumufumu-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # Node.jsのセットアップ (pnpmのキャッシュも有効化)
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: apps/fumufumu-backend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm test
